spec/open-api.yml

* Fixes object type of the ValidatedConfigV2 property.
* Makes text an optional element (nullable/required false)
```json
{
"errors": {
"runtime": [{ "id": "47b5f893-b617-498f-a644-09bbdf88f014", "errors": ["cannot initialise input plugin: john"] }],
"input": {
"syslog": [
{
"id": "49e66e6c-aac6-4ef4-8a9d-8829b91c72d2",
"property": "start",
"text": "",
"errors": ["Unknown syslog mode abc"]
}
]
},
"output": {},
"filter": {
"parser": [
{
"id": "9df81e1e-0504-4f8e-a186-7f19d432651c",
"property": "start",
"text": "",
"errors": ["missing 'key_name'"]
}
]
}
}
}
```

Fix type definition for runtime.

---

scripts/setup-tests.sh

Switch to using the microlith for API validation rather than running the compose stack.
Related to https://github.com/calyptia/cloud/issues/328 in that it simplifies testing. 

testing: move to using microlith

---

client/token/decode.go
client/token/decode_test.go

Decoding from project token is used across, lets make it a sub-package of the client.
This commits adds a non-signature verified version.
N/A
N/A

api/token: add sub-package for token decode.

---

client/pipeline_status.go
spec/open-api.yml
types/pipeline_status.go

Adding `?status=` query parameter, type and spec to the list of pipeline status history.
Closes https://github.com/calyptia/api/issues/46

add status filter

---

spec/open-api.yml
types/aggregator.go

* Add Version field to aggregator struct(s).
Note that tests will not be added until this change lands and cloud gets re-synced.
N/A.

aggregator: add version field.

---

client/pipeline.go
client/pipeline_test.go
spec/open-api.yml

Add support for paginated pipelines: updated the spec, and client.
Project pipelines are not implemented yet.
Please merge https://github.com/calyptia/api/pull/58 first.
https://github.com/calyptia/api/issues/50

paginated pipelines

---

client/membership.go
client/membership_test.go
client/pipeline.go
client/pipeline_config.go
client/pipeline_config_test.go
client/pipeline_file.go
client/pipeline_file_test.go
client/pipeline_port.go
client/pipeline_port_test.go
client/pipeline_secret.go
client/pipeline_secret_test.go
client/pipeline_test.go
client/resource_profile.go
client/resource_profile_test.go

Add pagination functionality to get pipelines from projects

---

types/agent.go
types/aggregator.go
types/pipeline.go

Add tag field on aggregator, agent and pipelines typess
fix #66

Add tags property to agent type

---

client/agent_test.go
client/aggregator_test.go
client/pipeline_test.go

fix lint reported by golangci-lint

---

types/agent.go
types/aggregator.go
types/environment.go

adding features to support the environement feature
[WIP]
#82 

Add environment id to agent

---

types/agent.go
types/aggregator.go
types/environment.go

Removing `project_id` from json API to follow the rest.
Renaming `environment` to `environmentName` to differentiate with its ID.
~~Removing `environment` from register/update agent and create/update aggregator since the environment should be read from the token.~~
Switching from `environment`(name) to `environmentID` at register/update agent and create/update aggregator.

fixes to new environments

---

spec/open-api.yml
types/pipeline.go
types/pipeline_config.go

These are the changes in the API for the forthcoming support for JSON and YAML fluent-bit configuration for pipelines.
Related to work in the cloud.

add config format

---

client/pipeline.go
client/pipeline_config.go
client/pipeline_status.go
client/pipeline_test.go
spec/open-api.yml
types/pipeline.go
types/pipeline_config.go
types/pipeline_status.go

Adds config_format param to listing statuses and single pipeline.
Remove config format to be a pointer were it didn't need to be.

add config format to statuses and single pipeline

---

client/environment.go
client/environment_test.go

Create API test for environments
#82

Create API test for environments

---

client/client_test.go
client/environment_test.go
go.mod
go.sum

Restoring update/delete environment tests as https://github.com/calyptia/cloud/pull/455 has been merged.
This PR follows https://github.com/calyptia/api/pull/95

client: uncomment update/delete env tests

---

client/environment.go
spec/open-api.yml
types/environment.go

Add name parameter to client, spec and type  to filter environtments by it.

Get environment by name

---

types/aggregator.go
types/pipeline.go

types: add metadata to aggregators

---

types/aggregator.go

These statuses are to add a presence indicator to the new core UI.
The idea is that a new core instance will have a status of `waiting` and once it receives a ping from the core-daemon it will change to `running`, if time passes without a ping from the core-daemon, the status will change to `terminated`.
https://github.com/calyptia/cloud/issues/491

types: add aggregator status

---

client/agent.go
client/aggregator.go
types/aggregator.go

- Add AggregatorPingResponse struct.

Add AggregatorPingResponse struct.

---

client/aggregator_test.go
spec/open-api.yml

1. Add tests to cover the aggregator ping endpoint.
2. Add openapi reference spec.

Add ping tests and spec.

---

client/aggregator_test.go
spec/open-api.yml
types/aggregator.go

Revert "types: add public ipv4 calyptia-core instance metadata for AWS"

---

.golangci.yml
client/agent.go
client/agent_test.go
client/aggregator.go
client/aggregator_test.go
spec/open-api.yml

This PR is a continuation 4/4 of issue [#97](https://github.com/calyptia/cli/issues/97). 
This requires https://github.com/calyptia/cloud/pull/507 to land.
Check [#506](https://github.com/calyptia/cloud/pull/506) for full context.

Add tests to validate issue #97

---

spec/open-api.yml
types/agent.go
types/aggregator.go

Return the environment name of the created aggregator
and agent objects
Required for fixing https://github.com/calyptia/cli/issues/97

Add environment to created aggregator/agent.

---

.github/workflows/lint.yml
.golangci.yml
client/client_test.go
client/trace.go
client/trace_test.go
spec/open-api.yml
types/trace.go

Updating the Go client with the new requests to work with trace sessions and records.
Still missing tests. Don't merge yet.
We are using this branch from the calyptia CLI to tests the whole flow first.

client: trace

---

types/aggregator.go
types/metric.go

Required type and params for supporting bulk pipeline metrics querying. 
Refers to https://github.com/calyptia/cloud/issues/528

Add types/params for bulk pipelines metrics.

---

client/trace_test.go
spec/open-api.yml
types/trace.go

Temporarily disable trace client tests for https://github.com/calyptia/cloud/pull/531

temporarily disable trace client tests

---

types/aggregator.go
types/metric.go

Change params types for pipelines metrics.

---

client/aggregator.go
client/aggregator_test.go
client/client_test.go
client/metric.go
client/metric_test.go

Review of https://github.com/calyptia/api/pull/125

#125 review

---

client/pipeline_test.go

Fix invalid pipeline config used during tests.

fix wrong fbit config during tests

---

spec/open-api.yml
types/aggregator.go

Adding the new bulk pipeline metrics endpoint to the spec.
Also added some `omitempty` json tags to core instance metadata; closing https://github.com/calyptia/api/issues/120

spec: bulk pipeline metrics

---

types/aggregator.go

Option to update core instance tags.

types: update core instance tags

---

.github/workflows/lint.yml
.golangci.yml
client/agent.go
client/agent_test.go
client/aggregator.go
client/aggregator_test.go
client/client_test.go
client/pipeline.go
client/pipeline_test.go
spec/open-api.yml

Adding the new bulk delete endpoints to both the spec and Go client.
Closes https://github.com/calyptia/api/issues/141

{spec,client}: bulk delete

---

client/pipeline_status_test.go
client/pipeline_test.go
spec/open-api.yml
types/pipeline.go
types/pipeline_status.go

This is a distinct implementation of events for statuses which would send them all within the status itself.
calyptia/cloud#553.

pipeline/events: add events to status.

---

types/fbit_config.go

See https://github.com/calyptia/cloud/issues/556

types: add reusable fluent-bit plugin configs

---

spec/open-api.yml

- Update cluster object specs/client/api

Update cluster object specs

---

spec/open-api.yml

Fix missing items property.

---

go.mod
go.sum

Update dependencies, CI cleanup

---

spec/open-api.yml

Refer to https://github.com/calyptia/cloud/pull/713

[spec] Add service to ConfigSectionKind

---

spec/open-api.yml

This pr closes calyptia/cloud#734 

Fix metrics summary object used on response of metrics

---

.github/workflows/lint.yml
scripts/run-tests.sh
scripts/setup-tests.sh

Support custom configuration, e.g. during testing of self-hosted.
Updated linting - Go linting was failing and has incompatible settings with /cloud which is where the linting should happen anyway before merging here. The other linters were in sequence so never fired, switched to a matrix for them.
The goal was to disable a check for the `/v1/verification_email` endpoint on self-hosted which has no Auth0 integration support.
Tested via: ` ./scripts/run-tests.sh --endpoint "[^(?:^/v1/verification_email)]"`
Self-hosted run via KIND with portforwarding to satisfy `localhost:5000`.
https://app.asana.com/0/1205296321537082/1206179657987322/f

scripts: add support for custom options to schemathesis

---

go.mod
go.sum
scripts/run-tests.sh

Re enabling schemathesis back in.
[sc-101457]

restore schemathesis
